#!/command/with-contenv bash

source /assets/functions/00-container
prepare_service all
PROCESS_NAME="postfix-relay"

configure_data_dir
configure_monitoring
configure_postfix

if var_true "${ENABLE_AUTH}" ; then
	sanity_var SMTP_USER "SMTP Username"
	sanity_var SMTP_PASS "SMTP Password"
	configure_sasl
fi

configure_summary

custom_scripts

chown -f -R postfix:postfix ${DATA_LOCATION}/{active,bounce,corrupt,defer,deferred,flush,hold,incoming,private,saved,trace,var}
chown -f -R postfix:postdrop ${DATA_LOCATION}/{maildrop,public}
if var_true "${ENABLE_HEADER_CHECKS}" ; then silent sudo -u postfix postmap "${DATA_PATH}"/header_checks ; fi
if var_true "${ENABLE_SMTP_HEADER_CHECKS}" ; then silent sudo -u postfix postmap "${DATA_PATH}"/header_checks ; fi
silent chown -f postfix:postfix ${DATA_LOCATION}/*.*
sudo -u postfix postmap lmdb:${DATA_LOCATION}/var/sasl_passwd

liftoff